language: generic
sudo: required
#os: windows
services:
  - docker

before_install:
  - docker build -t rtimbro185/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rtimbro185/docker-react npm run test