language: generic
sudo: required
#os: windows
services:
  - docker

before_install:
  - docker build -t rtimbro185/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rtimbro185/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-reate"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-464020980987"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY