version: '3'
services:
  web:
    stdin_open: true #4-1-2020 React App Exited With Code 0

    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app # maps the current folder outside the container to the current folder inside the container
    environment: 
      - CHOKIDAR_USEPOLLING=true # 4-21-2020 Windows not Detecting Changes - Docker Compose

  # set up second service for testing
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: # reruns when any files change
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]